name: job1
on: push

jobs:
    packer: 
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'

      steps:
      - name: Use my composite action
        uses: RachitGupta008/test-wif/actions/test@main
        with:
          input1: 'Some value'
