name: job
on: push

jobs:
    packer: 
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'
      steps:
       - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation and generate an access token.
       - id: 'auth'
         name: 'Authenticate to Google Cloud'
         uses: 'google-github-actions/auth@v1'
         with:
            token_format: 'access_token' # <--
            workload_identity_provider: 'projects/472475384454/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'gh-pipeline-sa@sandbox-dev-dbg.iam.gserviceaccount.com'
            access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)

       - id: 'access-secret'
         run: |-
            curl -X GET -H "Content-Type: application/json" -H  "x-goog-user-project: sandbox-dev-dbg"     https://dialogflow.googleapis.com/v3/projects/sandbox-dev-dbg/locations/global/agents/4d29473e-6d72-4491-a083-4c62ef6e159b/environments/840a4981-8cd2-4e52-89ff-c48023f52327/experiments \
              --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
